### ISSUE TITLE
Swig Python test fails

### ISSUE THREAD

**Issue by Sjors** [ElementsProject/libwally-core#109]
On macOS 10.14.5 with Python 3.7.3 and Swig 4.0.0 installed via Homebrew.

```sh
./configure --enable-debug --enable-export-all --enable-swig-python
make
make check
```

A bunch of tests pass and then:

```
Ran 1 test in 0.001s

OK
Traceback (most recent call last):
  File "swig_python/contrib/bip32.py", line 3, in <module>
    from wallycore import *
  File "/Users/sjors/dev/libwally-core/src/swig_python/wallycore/__init__.py", line 13, in <module>
    from . import libwallycore
ImportError: cannot import name 'libwallycore' from 'wallycore' (/Users/sjors/dev/libwally-core/src/swig_python/wallycore/__init__.py)
make[3]: *** [check-local] Error 1
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1
```

I noticed some commits referring to Swig 3.0, so maybe that's the issue? Unfortunately if I use `swig@3.04` then `make` fails with `Error: SWIG is not installed.`

**Comment by altafan** [comment]
same for me, but on macOS 10.12.6, did you solve @Sjors?
