### ISSUE TITLE
NPM install does not build javascript wrapper

### ISSUE THREAD

**Issue by 86667** [ElementsProject/libwally-core#175]
`wrap_js` does not install/build. This may be an issue with my configuration.

Install libwally-core as:
```
./tools/autogen.sh
./configure --enable-js-wrappers --disable-swig-python --disable-swig-java --enable-elements --enable-debug
make
``` 

When I `require(..../libwally-core/src/wrap_js)` and call via Node everything works fine. But when including this install in an npm `package.json`, or simply calling `npm install libwally-core/src/wrap_js\`, the following error occurs:

```
wallyjs@0.0.0 install /Users/tomos/lava-wallet/libwally-core/src/wrap_js
> node-gyp configure && node-gyp build
 CC(target) Release/obj.target/deps/src/combined.o
../src/combined.c:2:10: fatal error: ‘internal.c’ file not found
#include “internal.c”
     ^~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/deps/src/combined.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack   at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack   at ChildProcess.emit (events.js:321:20)
gyp ERR! stack   at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command “/usr/local/Cellar/node/13.8.0/bin/node” “/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js” “build”
gyp ERR! cwd /Users/tomos/lava-wallet/libwally-core/src/wrap_js
gyp ERR! node -v v13.8.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wallyjs@0.0.0 install: `node-gyp configure && node-gyp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wallyjs@0.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!   /Users/tomos/.npm/_logs/2020-02-13T12_06_21_382Z-debug.log
```

MacOs Catalina 10.15.3
Node v13.8.0
npm v6.13.6

**Comment by jgriffiths** [comment]
JS is now built differently, closing.
