### ISSUE TITLE
 stack-based bufferoverflow

### ISSUE THREAD

**Issue by p1ngfl0yd** [ElementsProject/libwally-core#81]
Hi Team,

### Summary

While fuzzing libwally-core using clang 6.0 with ASAN a stack-based buffer-overflow was observed in test_clear.c

**Vulnerable code from test_clear.c:**

```c
    for (i = 0; i < PTHREAD_STACK_MIN - len - 1; ++i)
        if (!memcmp(gstack + i, search, len)) {
            if (caller) {
                printf("Found %s secret at stack position %ld\n", caller, (long)i);
                dump_mem(search, len);
            }
            return true; /* Found */
        }
```

**Output from ASAN:**

```c
==97601==ERROR: AddressSanitizer: stack-buffer-underflow on address 0x7f5320c9a5a0 at pc 0x0000004aa159 bp 0x7f5320c9a590 sp 0x7f5320c99d40
READ of size 8 at 0x7f5320c9a5a0 thread T1
    #0 0x4aa158 in __interceptor_memcmp.part.273 (/home/zubin/Git/libwally-core/src/.libs/test_clear+0x4aa158)
    #1 0x50c17e in in_stack /home/zubin/Git/libwally-core/src/ctest/test_clear.c:73:14
    #2 0x50c17e in test_search /home/zubin/Git/libwally-core/src/ctest/test_clear.c:92
    #3 0x50c17e in run_tests /home/zubin/Git/libwally-core/src/ctest/test_clear.c:125
    #4 0x4df782 in __asan::AsanThread::ThreadStart(unsigned long, __sanitizer::atomic_uintptr_t*) (/home/zubin/Git/libwally-core/src/.libs/test_clear+0x4df782)
    #5 0x7f53205f86da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da)
    #6 0x7f531f95f88e in clone /build/glibc-OTsEL5/glibc-2.27/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

0x7f5320c9a5a0 is located 519584 bytes inside of 524288-byte region [0x7f5320c1b800,0x7f5320c9b800)
allocated by thread T0 here:
    #0 0x4d1cd0 in malloc (/home/zubin/Git/libwally-core/src/.libs/test_clear+0x4d1cd0)
    #1 0x50bc38 in checked_malloc /home/zubin/Git/libwally-core/src/ctest/test_clear.c:61:17
    #2 0x50bc38 in main /home/zubin/Git/libwally-core/src/ctest/test_clear.c:143
    #3 0x7f531f85fb96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310

Thread T1 created by T0 here:
    #0 0x4351c0 in __interceptor_pthread_create (/home/zubin/Git/libwally-core/src/.libs/test_clear+0x4351c0)
    #1 0x50bdc2 in main /home/zubin/Git/libwally-core/src/ctest/test_clear.c:154:11
    #2 0x7f531f85fb96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310

SUMMARY: AddressSanitizer: stack-buffer-underflow (/home/zubin/Git/libwally-core/src/.libs/test_clear+0x4aa158) in __interceptor_memcmp.part.273
Shadow bytes around the buggy address:
  0x0feae418b460: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0feae418b470: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0feae418b480: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0feae418b490: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0feae418b4a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0feae418b4b0: 00 00 00 00[f1]f1 f1 f1 00 f3 f3 f3 00 00 00 00
  0x0feae418b4c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0feae418b4d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0feae418b4e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0feae418b4f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0feae418b500: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==97601==ABORTING

```
Request team to have a look and validate.
Thanks.

**Comment by greenaddress** [comment]
Hi @p1ngfl0yd - thank you! will have a look and get back

**Comment by glslang** [comment]
this is expected due to the nature of the test itself and how  it sets up the custom stack.
